services:
  - type: web
    name: event-backend
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: DB_URL
        fromDatabase:
          name: event-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: event-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: event-db
          property: password
      - key: SPRING_MAIL_USERNAME
        value: tudasherxd@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: ajcsmhmxqbizykku

databases:
  - name: event-db
    databaseName: eventdb
    user: eventuser
    plan: free
